### ISSUE TITLE
Cannot get it to work on Ubuntu Server 64-bit 20.04 (with Xubuntu desktop)

### ISSUE THREAD

**Issue by victorbrca** [lcdwiki/LCD-show-ubuntu#9]
I have been trying to get this to work on a new install of Ubuntu server 64-bit 20.04 (with Xubuntu desktop) on a Raspberry Pi 3B (3.5 display) and I cannot.

Even after making manual changes the device gets stuck and won't boot. 

Anyone else able to get it to work PI3B?

**Comment by pierrard** [comment]
Hi  Victor, 
Same issue with Pi4 and MPI5008 (5" touch)
Check other opened issues; yours should have been added to existing ones instead of new issue.

Issue is with the compatibility of the driver with Ubuntu. 
Without touch driver, just forcing resolution,  screen worked fine in Ubuntu. When trying to get driver for Ubuntu server to activate touch is when it bricked my Pi.

What you described is same problem as mine and seems same (occurs at same point) as all the already opened issues for the Ubuntu driver.
As per YouTube videos, it is working fine with some other distributions.
Fingers crossed ...

**Comment by victorbrca** [comment]
@pierrard I did not see any open issues for my current setup (Ubuntu 20.04 64-bit on RPI3B). I did see other similar issues, but not for different Ubuntu versions and different boards (RPI4 is quite different than RPI3B). 

I did however find a solution and I got mine working. Mind you running Ubuntu 20.04 on RPI3B is not the best user experience. 

I will provide my feedback shortly.

**Comment by victorbrca** [comment]
If anyone is looking to get the screen to work specifically on RPI3b with Ubuntu 20.04 64-bit, I was able to get it to work.
 
Instructions [here](https://blog.victormendonca.com/2020/10/13/how-to-install-waveshare-3.5inch-lcd-on-ubuntu-20.04/)
Ansible playbook [here](https://github.com/victorbrca/waveshare35-rpi3b-ubuntu-20.04-64)
